"""Initial Migration

Revision ID: 13c138b41b6f
Revises: c7e326c7409e
Create Date: 2022-05-16 15:19:53.618449

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '13c138b41b6f'
down_revision = 'c7e326c7409e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_comments_post_comment', table_name='comments')
    op.drop_column('comments', 'post_comment')
    op.drop_index('ix_posts_content', table_name='posts')
    op.drop_index('ix_posts_title', table_name='posts')
    op.add_column('users', sa.Column('name', sa.String(), nullable=True))
    op.add_column('users', sa.Column('profile_pic', sa.String(), nullable=True))
    op.drop_column('users', 'profile_pic_path')
    op.drop_column('users', 'username')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('username', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('profile_pic_path', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('users', 'profile_pic')
    op.drop_column('users', 'name')
    op.create_index('ix_posts_title', 'posts', ['title'], unique=False)
    op.create_index('ix_posts_content', 'posts', ['content'], unique=False)
    op.add_column('comments', sa.Column('post_comment', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.create_index('ix_comments_post_comment', 'comments', ['post_comment'], unique=False)
    # ### end Alembic commands ###
