"""Initial Migration

Revision ID: cc1df4b7dbdd
Revises: e18177a1386a
Create Date: 2022-05-17 11:32:25.484767

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cc1df4b7dbdd'
down_revision = 'e18177a1386a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('downvote',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('downvotes', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('post_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('upvote',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('upvotes', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('post_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_column('posts', 'downvotes')
    op.drop_column('posts', 'upvotes')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('upvotes', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('posts', sa.Column('downvotes', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_table('upvote')
    op.drop_table('downvote')
    # ### end Alembic commands ###
